import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const font = Poppins({
  subsets:["latin"],
  weight:["600"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: {
  children: React.ReactNode;
  modal:React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} flex flex-col min-h-screen bg-background text-foreground`}>
        <Navbar />
        <div className="min-h-screen bg-background">
          {children}
        </div>
        {modal}
      </body>
    </html>
  );
}